server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codelab_db?serverTimezone=UTC&useSSL=false
    username: codelab
    password: codelab
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect